[package]
name = "ape"
version = "0.1.0"
authors = ["Pete Gadomski <pete.gadomski@gmail.com>"]


[dependencies]
clap = { version = "2.32", features = ["yaml"] }
las = "0.6"
nalgebra = "0.16"
spade = "1.6"
